In [1]:
import numpy as np
np.random.seed(0)
from env.EV_Sce_Env import EV_Sce_Env

env = EV_Sce_Env('test_2', seed=0, ps=False)

In [2]:
env.reset()
agents_total_reward = np.array([0.0 for _ in range(env.agent_num)])
print(env.caction_list)

[1.5, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95, 1.0]


In [3]:
env.step(([10, 0], [4, 4]))

(array([[0. , 0.4, 0.5, 0. , 0. , 0. , 1. , 0. , 0. , 0. ],
        [0. , 0.4, 0.5, 0. , 0. , 0. , 1. , 0. , 0. , 0. ]], dtype=float32),
 array([[[0., 0.],
         [0., 1.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],
 
        [[0., 0.],
         [0., 1.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]], dtype=float32),
 array([[0., 0., 1., 0., 1.],
        [0., 0., 1., 0., 1.]], dtype=float32),
 array([0.4, 0.5, 0. , 0. , 0. , 1. , 0. , 0. , 0. , 0.4, 0.5, 0. , 0. ,
        0. , 1. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ], dtype=float32),
 array([[0., 0., 0., 0.],
        [0., 0., 1., 1.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], dtype=float32),
 array([[0.],
        [0.]], dtype=float32),
 array([[0.],
        [0.]], dtype=float32),
 array([[-40.],
        [-40.]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([0., 0.], dtype=float32),
 [0, 1],
 [True, True],
 [],
 [])

In [4]:
env.render()

Time: 0.41 h
EV_0:
	 SOC:0.400%   Pos:0-1   Reward:-40.00000   Using time:0.400h   Charing times:0   Charing SOC:0.000%
	 Action_list:  [1]
	 Action_type:  ['r']
	 Route:  ['0-1']
EV_1:
	 SOC:0.400%   Pos:0-1   Reward:-40.00000   Using time:0.400h   Charing times:0   Charing SOC:0.000%
	 Action_list:  [1]
	 Action_type:  ['r']
	 Route:  ['0-1']
CS_0: 0.000	0.000	
CS_1: 0.000	0.000	
CS_2: 0.000	0.000	
CS_3: 0.000	0.000	
CS_4: 0.000	0.000	
Global_inf:  [0. 0. 0. 0. 0.]
